### ISSUE TITLE
 from .cv2 import * ImportError: numpy.core.multiarray failed to import >>> 

### ISSUE THREAD

**Issue by BernardNyarko** [EbenKouao/pi-camera-stream-flask#13]
Hi Eben, thanks for the video on how to make a remote viewable camera with raspberry pi (Beginner project). However, I've been having issues running the main.py as it keeps giving me an error with regards to numpy. I've uninstalled and installed different versions of numpy to no avail. can you please help?. Below is the error I receive when I run the main.py code.

 
python 3.7.3 (/usr/bin/python3)
>>> %Run camera.py
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "/home/pi/pi-camera-stream-flask/camera.py", line 5, in <module>
    import cv2
  File "/usr/local/lib/python3.7/dist-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
>>>

**Comment by BernardNyarko** [comment]
Don't bother Eben, I just got it fixed. The command "pip3 install --upgrade numpy" did the trick.

**Comment by BjoernLuig** [comment]
I got exactly the same problem but "pip3 install --upgrade numpy" didn't fix it. Any ideas?

**Comment by BernardNyarko** [comment]
Sorry about that. If it didn't work then I don't know of any other
solutions to the problem.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by nbosio1001** [comment]
Why is this project missing a requirements.txt file?
