### ISSUE TITLE
its not working - what is wrong?

### ISSUE THREAD

**Issue by Stb1976** [EbenKouao/pi-camera-stream-flask#15]
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x1937060 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
Traceback (most recent call last):
  File "/home/pi/pi-camera-stream-flask/main.py", line 12, in <module>
    pi_camera = VideoCamera(flip=False) # flip pi camera if upside down.
  File "/home/pi/pi-camera-stream-flask/camera.py", line 13, in __init__
    self.vs = PiVideoStream().start()
  File "/usr/local/lib/python3.7/dist-packages/imutils/video/pivideostream.py", line 10, in __init__
    self.camera = PiCamera()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 433, in __init__
    self._init_preview()
  File "/usr/lib/python3/dist-packages/picamera/camera.py", line 513, in _init_preview
    self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
  File "/usr/lib/python3/dist-packages/picamera/renderers.py", line 558, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/usr/lib/python3/dist-packages/picamera/mmalobj.py", line 2212, in enable
    prefix="Failed to enable connection")
  File "/usr/lib/python3/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
picamera.exc.PiCameraMMALError: Failed to enable connection: Out of resources
Exception ignored in: <function VideoCamera.__del__ at 0xac399228>
Traceback (most recent call last):
  File "/home/pi/pi-camera-stream-flask/camera.py", line 18, in __del__
    self.vs.stop()
AttributeError: 'VideoCamera' object has no attribute 'vs'

Please help.

**Comment by kanduko** [comment]
I have the same issue

**Comment by kanduko** [comment]
I had the same issue. My problem was that I forgot to turn on the camera interface in the Interfacing Options with 'sudo raspi-config'

**Comment by AokiAhishatsu** [comment]
>  turn on the camera interface in the Interfacing Options with 'sudo raspi-config'
This should be in the

**Comment by Adnan4290** [comment]
I have the same issue but turning on the camera doesn't work, maybe it is for debian 10 version of pi OS?
