### ISSUE TITLE
Beta image of Raspberry Pi Camera Stream

### ISSUE THREAD

**Issue by iflybywireless** [EbenKouao/pi-camera-stream-flask#17]
Hi there, The "Download Beta image of Raspberry Pi Camera Stream" image returns a 404 error, Was this ever done?

https://github.com/EbenKouao/pi-camera-stream-flask/blob/master/img/readme/%5B%5D.png

**Comment by iflybywireless** [comment]
It failed to install at the sudo pip3 install opencv-contrib-python part:
The tail of the output
  [100%] Linking CXX static library ../../lib/libopencv_stereo.a
  [100%] Built target opencv_stereo
  [100%] Generate files for Python bindings and documentation
  Note: Class Feature2D has more than 1 base class (not supported by Python C extensions)
        Bases:  cv::Algorithm, cv::class, cv::Feature2D, cv::Algorithm
        Only the first base class will be used
  Note: Class detail_GraphCutSeamFinder has more than 1 base class (not supported by Python C extensions)
        Bases:  cv::detail::GraphCutSeamFinderBase, cv::detail::SeamFinder
        Only the first base class will be used
  [100%] Built target gen_opencv_python_source
  [100%] Building CXX object modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o
  c++: fatal error: Killed signal terminated program cc1plus
  compilation terminated.
  make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/build.make:76: modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 1
  make[1]: *** [CMakeFiles/Makefile2:5207: modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
  make: *** [Makefile:166: all] Error 2
  Traceback (most recent call last):
    File "/tmp/pip-build-env-8nyb7ntq/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 593, in setup
      cmkr.make(make_args, env=env)
    File "/tmp/pip-build-env-8nyb7ntq/lib/python3.7/site-packages/skbuild/cmaker.py", line 515, in make
      os.path.abspath(CMAKE_BUILD_DIR())))
  
  An error occurred while building with CMake.
    Command:
      cmake --build . --target install --config Release --
    Source directory:
      /tmp/pip-install-bkk_bvnp/opencv-contrib-python
    Working directory:
      /tmp/pip-install-bkk_bvnp/opencv-contrib-python/_skbuild/linux-armv7l-3.7/cmake-build
  Please see CMake's output for more information.
  
  ----------------------------------------
  Failed building wheel for opencv-contrib-python
  Running setup.py clean for opencv-contrib-python
Failed to build opencv-contrib-python
Installing collected packages: opencv-contrib-python
  Running setup.py install for opencv-contrib-python ...

Then the PI locked up.
I've tried different SDCards and a fresh download but still fails...

**Comment by iflybywireless** [comment]
The Strange thing is I did  have it working about a month ago, no problems. Until I had a SDCard corruption and had to rebuild the system. BTW I'm only using a PI 3 V1.2 but as I said it did work before.
