### ISSUE TITLE
Not working anymore (september 2022)

### ISSUE THREAD

**Issue by joancatala** [EbenKouao/pi-camera-stream-flask#26]
I follow the instructions last night and there is no libqtgui4 and libqt4-test
And there is a version problem also with numpy.

So, at the end when you start with sudo python3 pi-camera-stream-flask/main.py there are some errors.

**Comment by matttb1984** [comment]
Same for me.  Here's what I get when I try to run the script.  This is after installing a few missing packages too.

`pi@raspberrypicam:~ $ sudo python3 /home/pi/pi-camera-stream-flask/main.py
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
Traceback (most recent call last):
  File "/home/pi/pi-camera-stream-flask/main.py", line 7, in <module>
    from camera import VideoCamera
  File "/home/pi/pi-camera-stream-flask/camera.py", line 5, in <module>
    import cv2 as cv
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.9/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: numpy.core.multiarray failed to import
pi@raspberrypicam:~ $ `

**Comment by carpequarq** [comment]
I found on issue 13 the solution to what you have above.
I tried running the numpy upgrade without sudo
  _pip3 install --upgrade numpy_
per [BernardNyarko](https://github.com/BernardNyarko)

and running main.py without sudo as well
  _python3 /home/pi/pi-camera-stream-flask/main.py_
per [BjoernLuig](https://github.com/BjoernLuig)

I found the solution under issue 13:
https://github.com/EbenKouao/pi-camera-stream-flask/issues/13
